# in aurora_agent/agent_brains/experts/jupyter/state.py
from typing import TypedDict, Optional, List, Dict, Any

class JupyterExpertState(TypedDict):
    """
    Defines the data structure (the 'memory') that flows through the Jupyter expert graph.
    """
    # --- Inputs from the main orchestrator ---
    mission_prompt: str
    current_url: str
    mission_steps: Optional[List[str]]  # The agent's own breakdown of the mission
    current_step_index: int             # Which step we are currently on
    scope_selector: Optional[str] # The locator for the main content area

    # --- Information gathered and generated during the run ---
    code_to_execute: Optional[str]        # Python code generated by the LLM
    script_to_run: Optional[str]          # Name of a pre-recorded UI script to run
    
    # --- Outputs of the run ---
    tool_result: Optional[str]            # The direct output from a tool after execution
    final_output: Optional[str]           # The final summary for the higher-level graph
    error_message: Optional[str]          # Any errors encountered during the process