apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-bubble
  labels:
    app: session-bubble
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-bubble
  template:
    metadata:
      labels:
        app: session-bubble
    spec:
      containers:
      - name: session-bubble
        # This image path is a placeholder. Your CI/CD pipeline will replace it.
        image: gcr.io/your-gke-project-id/session-bubble:placeholder
        ports:
        - name: vnc
          containerPort: 6901
          
        # This section loads environment variables from your Secrets and ConfigMap
        envFrom:
        - secretRef:
            name: app-secrets
        - configMapRef:
            name: app-config
        
        # This section sets the paths for your mounted JSON key files
        env:
        - name: GOOGLE_SERVICE_ACCOUNT_KEY_PATH
          value: "/etc/secrets/google-sa/service-account-key.json"
        - name: GOOGLE_SERVICE_ACCOUNT_KEY_PATH_DOCS
          value: "/etc/secrets/google-docs-api/docs_api.json"
        - name: DISPLAY
          value: ":99"

        # This section mounts the secret JSON files into the container's filesystem
        volumeMounts:
        - name: google-sa-key-volume
          mountPath: "/etc/secrets/google-sa"
          readOnly: true
        - name: google-docs-api-key-volume
          mountPath: "/etc/secrets/google-docs-api"
          readOnly: true
          
        # This section defines resource requests and limits for stability
        resources:
          requests: { cpu: "250m", memory: "512Mi" }
          limits: { cpu: "1", memory: "1Gi" }
            
        # These probes check if your application is healthy
        startupProbe:
          tcpSocket: { port: 6901 }
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 6

        livenessProbe:
          tcpSocket: { port: 6901 }
          periodSeconds: 20
          failureThreshold: 3

        readinessProbe:
          tcpSocket: { port: 6901 }
          periodSeconds: 10
          failureThreshold: 3
          
      # This section defines the volumes that hold the secret files
      volumes:
      - name: google-sa-key-volume
        secret:
          secretName: google-sa-key # Must match the secret created by the workflow
      - name: google-docs-api-key-volume
        secret:
          secretName: google-docs-api-key # Must match the secret created by the workflow

      # This enforces non-root security at the Kubernetes level
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        
      terminationGracePeriodSeconds: 30