apiVersion: v1
kind: Service
metadata:
  # A descriptive name for the Service object itself
  name: session-bubble-vnc-service
spec:
  # This selector is crucial. It tells the Service to send traffic
  # to any pod that has the label "app: session-bubble".
  selector:
    app: session-bubble
  
  ports:
    - protocol: TCP
      # This is the external port on the load balancer that you will connect to.
      port: 6901
      # This is the internal port on your container that traffic will be sent to.
      targetPort: 6901
      
  # This is the most important line. It tells GKE to create an 
  # external network load balancer with a public IP address.
  type: LoadBalancer