name: Build and Deploy to VM

# This pipeline runs every time you push to the 'main' branch
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    # Use a standard Linux server provided by GitHub
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository's code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub using the secrets you stored
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Set up Docker Buildx for cross-platform building
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Build the amd64 image and push it directly to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platform: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/session-bubble:latest

      # Step 5: SSH into the VM and deploy the new image
      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull the new version of the image from Docker Hub
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/session-bubble:latest
            
            # Stop and remove the old container if it exists
            docker stop session-bubble || true
            docker rm session-bubble || true
            
            # Run the new container with the exact same command as before
            docker run \
              -d \
              --restart always \
              -p 6901:6901 \
              -p 127.0.0.1:8765:8765 \
              -p 127.0.0.1:8766:8766 \
              --name session-bubble \
              ${{ secrets.DOCKERHUB_USERNAME }}/session-bubble:latest